name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build Frontend Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the frontend Docker image
      - name: Build frontend image
        run: |
          # Change to the frontend directory before building the Docker image
          cd /home/atif/Project/frontend
          # Build the image from the Dockerfile in the frontend directory
          docker build -f Dockerfile -t frontend:latest .

  # Job 2: Deploy Frontend to Contabo VPS
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # SSH into VPS and pull the latest frontend Docker image
            docker pull frontend:latest
            # Change to the directory where docker-compose.yml is located on the VPS
            cd /home/atif/Project/frontend  # Update the path to your frontend directory
            # Use Docker Compose to bring up the frontend service
            docker-compose -f docker-compose.frontend.yml up -d
            # Optionally run frontend image directly (if needed)
            docker run -d -p 3000:80 frontend:latest

