name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    environment: First-Step

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t yourdockerhubusername/frontend:latest -f frontend/Dockerfile .
          docker push yourdockerhubusername/frontend:latest

      # Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t yourdockerhubusername/backend:latest -f backend/Dockerfile .
          docker push yourdockerhubusername/backend:latest

  deploy:
    name: Deploy to Contabo VPS
    needs: build
    runs-on: ubuntu-latest
    environment: Second-Step

    steps:
      # SSH into Contabo VPS and deploy
      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull latest Docker images
            docker pull yourdockerhubusername/frontend:latest
            docker pull yourdockerhubusername/backend:latest

            # Start services with Docker Compose
            cd /path/to/your/project
            docker-compose up -d

